# Generated by Django 5.0.2 on 2024-03-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_for_delivery',
            new_name='due_date',
        ),
    ]
