# Generated by Django 5.0.6 on 2024-05-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_list_task_related_list_remove_task_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='dead_line',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
    ]
