# Generated by Django 5.0.2 on 2024-03-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_board_project_board_alter_project_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
    ]
