# Generated by Django 5.0.3 on 2024-04-21 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_board_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='due_date',
        ),
    ]
